env:
  es6: true
  browser: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - '@alex-taxiera/eslint-config-esm'
  - 'plugin:react/recommended'
rules: {
  'react/prop-types': ['warn'],
  'no-console': ['warn']
}
